services:
  fiber:
    # Dockerfile: https://github.com/Flouse/cfn-node/blob/develop/Dockerfile
    # ghcr: https://github.com/Flouse/cfn-node/pkgs/container/cfn-node
    container_name: fiber-testnet-node
    # https://github.com/Flouse/ckb-fiber-docker/pkgs/container/ckb-fiber
    image: ghcr.io/flouse/ckb-fiber:v0.0.1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 100M
    volumes:
    - cfn-data-20241229:/fiber
    - ./testnet-config.yml:/fiber/.fiber-node/config.yml:ro
    - ./testnet.key:/fiber/.fiber-node/ckb/key:ro
    ports:
    - 14228:8228
    # Allowing arbitrary machines to access the JSON-RPC port is dangerous and strongly discouraged.
    # Please strictly limit the access to only trusted machines.
    - 127.0.0.1:14227:8227
    environment:
    # Add any additional environment variables needed by CKB Fiber node
    - RUST_LOG=info
    command: [
      # TODO: init ckb wallet if it doesn't exist
      "fnn"
    ]

# Temp logs
# -c, --config <CONFIG_FILE> config file [default: "/root/.fiber-node/config.yml" or $BASE_DIR/config.yml]
# -d, --dir <BASE_DIR> base directory for all [default: "/root/.fiber-node"]

volumes:
  cfn-data-20241229:
    driver: local
