services:
  fiber:
    # Dockerfile: https://github.com/Flouse/cfn-node/blob/develop/Dockerfile
    # ghcr: https://github.com/Flouse/ckb-fiber-docker/pkgs/container/ckb-fiber
    container_name: fiber-testnet-node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FIBER_VERSION: v0.4.0
        CKB_CLI_VERSION: v1.12.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 100M
    environment:
    # Add any additional environment variables needed by CKB Fiber node
    - RUST_LOG=info
    volumes:
    - cfn-data:/fiber/.fiber-node
    - ./testnet-config.yml:/fiber/.fiber-node/config.yml:ro
    # If the key is not provided, entrypoint will generate one.
    # - ./testnet.key:/fiber/.fiber-node/ckb/key:ro
    ports:
    - 58228:8228
    # Allowing arbitrary machines to access the JSON-RPC port is dangerous and strongly discouraged.
    # Please strictly limit the access to only trusted machines.
    - 127.0.0.1:58227:8227
    user: fiber

volumes:
  cfn-data:
    driver: local
