services:
  fiber:
    container_name: fiber-testnet-node
    # Build the image locally, or use the pre-built image from GitHub Container Registry (ghcr)
    # ghcr: https://github.com/Flouse/ckb-fiber-docker/pkgs/container/ckb-fiber
    #
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     FIBER_VERSION: v0.4.2
    #     CKB_CLI_VERSION: v1.12.0
    #
    # https://github.com/Flouse/ckb-fiber-docker/pkgs/container/ckb-fiber/377140523?tag=v0.4.2
    image: ghcr.io/flouse/ckb-fiber:v0.4.2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 100M
    environment:
    # Add any additional environment variables needed by CKB Fiber node
    - RUST_LOG=info
    volumes:
    - cfn-data:/fiber/.fiber-node
    - ./testnet-config.yml:/fiber/.fiber-node/config.yml
    # If the key is not provided, entrypoint.sh will generate one.
    # - ./testnet.key:/fiber/.fiber-node/ckb/key
    ports:
    - 58228:8228            # P2P port
    # Allowing arbitrary machines to access the JSON-RPC port is dangerous and strongly discouraged.
    # Please strictly limit the access to only trusted machines.
    - 127.0.0.1:58227:8227  # JSON-RPC port
    command: [
      "fnn",
      # node name to be announced to fiber network [env: FIBER_ANNOUNCED_NODE_NAME]
      "--fiber-announced-node-name", "FTN005",
      # addresses to be announced to fiber network [env: FIBER_ANNOUNCED_ADDRS=]
      # TODO: "--fiber-announced-addrs", "58228"
    ]

volumes:
  cfn-data:
    driver: local
