# Docker relies on networks for internal container communication. Containers that reside on the same
# network will be able to reach each other using either the internal IP address or the name of the
# service. Containers that need external visibility (from the host) will need to publish a port via
# the docker-compose.yml file (Docker will automatically handle NAT, firewall, and port forwarding).
networks:
  default:
    name: fiber-internal-network
    ipam:
      config:
        - subnet: 172.32.21.0/24     # Static Range (172.32.21.2-127)
          ip_range: 172.32.21.128/25 # Dynamic Range
          gateway: 172.32.21.1

services:
  fiber:
    container_name: fiber-testnet-node
    # Build the image locally, or use the pre-built image from GitHub Container Registry (ghcr)
    # ghcr: https://github.com/Flouse/ckb-fiber-docker/pkgs/container/ckb-fiber
    #
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     FIBER_VERSION: v0.5.1
    #     CKB_CLI_VERSION: v1.12.0
    #
    # https://github.com/Flouse/ckb-fiber-docker/pkgs/container/ckb-fiber/413695181?tag=main
    image: ghcr.io/flouse/ckb-fiber:main
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 100M
    environment:
    # Add any additional environment variables needed by CKB Fiber node
    - RUST_LOG=info
    env_file: .env
    volumes:
    - cfn-data:/fiber/.fiber-node
    - ./testnet-config.yml:/fiber/.fiber-node/config.yml
    # If the key is not provided, entrypoint.sh will generate one.
    # - ./testnet.key:/fiber/.fiber-node/ckb/key
    networks:
      default:
        # The IPv4 address of the container.
        ipv4_address: 172.32.21.2
    ports:
    - 58228:8228            # P2P port
    # Allowing arbitrary machines to access the JSON-RPC port is dangerous and strongly discouraged.
    # Please strictly limit the access to only trusted machines.
    - 127.0.0.1:58227:8227  # JSON-RPC port
    command: [
      "fnn",
      # Setup BASE_DIR
      "--dir", "/fiber/.fiber-node",
      # node name to be announced to fiber network [env: FIBER_ANNOUNCED_NODE_NAME]
      "--fiber-announced-node-name", "FTN20250415",
      # addresses to be announced to fiber network [env: FIBER_ANNOUNCED_ADDRS=]
      # TODO: "--fiber-announced-addrs", "58228"
    ]

volumes:
  cfn-data:
    driver: local
