# List of enabled services
services:
- fiber
- rpc
- ckb


# Fiber network configuration
fiber:
  # Local P2P network listening address
  listening_addr: "/ip4/0.0.0.0/tcp/8228"

  # Bootstrap nodes for initial network connection
  bootnode_addrs:
  - "/ip4/54.179.226.154/tcp/8228/p2p/Qmes1EBD4yNo9Ywkfe6eRw9tG1nVNGLDmMud1xJMsoYFKy"
  - "/ip4/54.179.226.154/tcp/18228/p2p/QmdyQWjPtbK4NWWsvy8s69NGJaQULwgeQDT5ZpNDrTNaeV"

  # Whether to announce your listening address to other peers
  announce_listening_addr: true

  # chain spec, can be mainnet | testnet | "path to chain spec file"
  chain: testnet

  # lock script configurations related to fiber network
  # https://github.com/nervosnetwork/fiber-scripts/blob/main/deployment/testnet/migrations/2024-09-14-084742.json
  scripts:
  - name: FundingLock
    script:
      code_hash: 0x6c67887fe201ee0c7853f1682c0b77c0e6214044c156c7558269390a8afa6d7c
      hash_type: type
      args: 0x
    cell_deps:
    - out_point:
        tx_hash: 0x89af398edc7ed0054506b33349b031097d94378e11e77bf0690ee69d82623a43
        index: 0x0
      dep_type: code
    - out_point:
        tx_hash: 0xbfd6d68b328a02606f1f65ee0f79f8ed5f76dfe86998c7aaa9ee4720d53f4c49 # ckb_auth
        index: 0x0
      dep_type: code
  - name: CommitmentLock
    script:
      code_hash: 0x740dee83f87c6f309824d8fd3fbdd3c8380ee6fc9acc90b1a748438afcdf81d8
      hash_type: type
      args: 0x
    cell_deps:
    - out_point:
        tx_hash: 0x89af398edc7ed0054506b33349b031097d94378e11e77bf0690ee69d82623a43
        index: 0x1
      dep_type: code
    - out_point:
        tx_hash: 0xbfd6d68b328a02606f1f65ee0f79f8ed5f76dfe86998c7aaa9ee4720d53f4c49 #ckb_auth
        index: 0x0
      dep_type: code


# RPC service configuration
rpc:
  # RPC server listening address
  # Since this config is used in a docker container, we allow all machines to access the RPC port.
  listening_addr: "0.0.0.0:8227"


# CKB node configuration
ckb:
  # CKB node RPC endpoint, TODO: ckb rpc load balancing for https://github.com/nervosnetwork/ckb/wiki/Public-JSON-RPC-nodes
  rpc_url: "https://testnet.ckbapp.dev/"
  udt_whitelist:
  # https://testnet.explorer.nervos.org/xudt/0x07ac97b5ff3df4b49f59a59f4d80d33d22c1263a57467c512c93b9c29b7a0de3
  - name: USDI
    script:
      code_hash: 0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037
      hash_type: type
      args: 0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f
    cell_deps:
    - tx_hash: 0x03d029480416c2fc927dfbfe0ed1916ffaf55d1e1f3146c55cf2d3dd5e674e61
      index: 0
      dep_type: code
    auto_accept_amount: 10
  # https://testnet.explorer.nervos.org/xudt/0x45b32a2bc4285d0a09678eb11960ddc8707bc2779887a09d482e9bfe9a2cdf52
  - name: RUSD
    script:
      code_hash: 0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a
      hash_type: type
      args: 0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b
    cell_deps:
    - tx_hash: 0xed7d65b9ad3d99657e37c4285d585fea8a5fcaf58165d54dacf90243f911548b
      index: 0
      dep_type: code
    auto_accept_amount: 1000000000
