name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    environment: testnet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
    - run: bun install
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Start containers
      run: |
        # Check if the testnet.key is available in GitHub secrets
        if [[ -n "${{ secrets.CKB_TESTNET_KEY }}" ]]; then
          echo "${{ secrets.CKB_TESTNET_KEY }}" > testnet.key
          echo "Uncommenting the line for testnet.key in docker-compose.yml"
          sed -i 's|# - ./testnet.key:/fiber/.fiber-node/ckb/key:ro|- ./testnet.key:/fiber/.fiber-node/ckb/key:ro|' docker-compose.yml
        fi

        # Start the Docker containers in detached mode
        docker compose up -d

    - name: Wait for services to be healthy
      run: |
        echo "Waiting for services to start..."
        for i in $(seq 1 30); do # Timeout after 30 * 10 = 300 seconds (5 minutes)
          if [[ $(docker inspect -f '{{.State.Health.Status}}' fiber-testnet-node) == "healthy" ]]; then
            echo "Fiber testnet node is not healthy"
            break
          fi
          sleep 10
        done

        docker compose ps
        echo "Checking if the fiber-testnet-node is healthy"

    - name: Verify port accessibility
      run: |
        nc -vz localhost 58228
        nc -vz localhost 58227

    - name: Test RPC endpoint
      run: |
        response=$(curl -s -X POST -H "Content-Type: application/json" \
          --data '{"id":2, "jsonrpc":"2.0", "method":"node_info", "params":[]}' http://localhost:58227)
        echo "Fiber Node info:"
        echo "$response" | jq .

        # Check if the response contains the expected version
        if echo "$response" | jq -e '.result.version' > /dev/null; then
          echo "RPC test passed: Version found"
        else
          echo "RPC test failed: Version not found in response"
          exit 1
        fi

    - name: Read ckb_rpc_url from testnet-config.yml
      run: |
        ckb_rpc_url=$(yq eval '.ckb.rpc_url' testnet-config.yml)
        echo "CKB_RPC_URL: $ckb_rpc_url"
        echo "CKB_RPC_URL=$ckb_rpc_url" >> $GITHUB_ENV

    - name: Get Testnet Address
      run: |
        # import the key into https://github.com/nervosnetwork/ckb-cli and extract the address
        TESTNET_ADDRESS=$(echo -e "\n" \
          | docker compose exec fiber ckb-cli account import --privkey-path /fiber/.fiber-node/ckb/key \
          | grep -A 1 'testnet:' | grep 'ckt1' | awk '{print $2}' | head --lines=1)
        echo "Testnet address: $TESTNET_ADDRESS"
        echo "CKB_TESTNET_ADDRESS=$TESTNET_ADDRESS" >> $GITHUB_ENV

    - name: Get Balance and get faucet if the balance is less than 10000 CKB
      env:
        MINIMUM_CKB: 10000
      run: |
        balance=$(docker compose exec fiber ckb-cli --url "${{ env.CKB_RPC_URL }}" \
          wallet get-capacity --address "${{ env.CKB_TESTNET_ADDRESS }}")
        echo "Balance of ${{ env.CKB_TESTNET_ADDRESS }}: $balance"

        # Extract the numeric part of the balance
        balance_ckb=$(echo "$balance" | grep -oP '\d+\.\d+' | awk '{print int($1)}')
        echo "Balance in CKB: $balance_ckb"

        if [[ "$balance_ckb" -lt ${{ env.MINIMUM_CKB }} ]]; then
          echo "Balance $balance_ckb CKB is less than ${{ env.MINIMUM_CKB }} CKB, requesting faucet"
          response=$(curl -s "https://nervos-functions.vercel.app/api/faucet?target_ckt_address=${{ env.CKB_TESTNET_ADDRESS }}")
          echo "$response" | jq .
        else
          echo "Balance $balance_ckb CKB is sufficient."
        fi

    - name: Fetch Public Fiber Nodes from https://testnet.explorer.nervos.org/fiber/graph/nodes
      run: |
        node_list=$(curl -s https://testnet-api.explorer.nervos.org/api/v2/fiber/graph_nodes)
        echo "Node List:"
        echo "$node_list" | jq .

    - run: bun test
    - run: bun start
    
    - name: Open channel
      run: |
        bun run script/open-channel.ts \
          --peer_id 03623b6095f393af50226b4451441fc0a6446dd63e0a833a85b621f994e0e323f9

    - name: Monitor memory usage
      if: always()
      run: docker stats --no-stream fiber-testnet-node --format "{{.MemUsage}}"

    - name: Stop containers
      if: always()
      run: |
        docker compose down -v
        echo "Removing the testnet.key file if it was created"
        if [[ -f testnet.key ]]; then
          rm testnet.key
        fi
